# Generates a TGT and saves it to the database
# Ticket will be generated by SecureRandom.base58
# Returns a cookie_hash like:
# => { value: 'SAMPLE_TGT', expires: 20.minutes.from_now }
module Tickets
  class TGTGenerator
    COOKIE_DURATION = 20.minutes

    def generate_ticket(username)
      store_ticket(username)
      ticket_hash
    end

    private

    def store_ticket(username)
      TGTCookie.create(username: username, cookie: ticket)
    end

    def ticket
      @ticket ||= SecureRandom.base58(24)
    end

    def ticket_hash
      { value: ticket, expires: COOKIE_DURATION.from_now }
    end
  end
end
