AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 80

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true
