# Generates a TGT and saves it to the database
# Ticket will be generated by SecureRandom.base58
# Returns a cookie_hash like:
# => { value: 'SAMPLE_TGT', expires: 20.minutes.from_now }
module Tickets
  module Generators
    class TGTGenerator
      def generate_ticket(username)
        store_ticket(username)
        ticket
      end

      private

      def store_ticket(username)
        TGTCookie.create(username: username, cookie: ticket)
      end

      def ticket
        @ticket ||= SecureRandom.base58(24)
      end
    end
  end
end
